### ISSUE TITLE
라이브러리 최신으로 갱신하기

### ISSUE THREAD

**Issue by ojh999** [ubinos/question_and_answer#10]
유비노스 라이브러리를 최신으로 갱신하는 과정에서 유비노스와 유비노스메인 체인지가 안되는 것 같습니다.
![ubinos](https://github.com/ubinos/question_and_answer/assets/164192164/80bed668-22e7-4d54-9c1b-18423b3e9e41)

**Comment by siminsungho** [comment]
From ~, to ~, 둘 다  check 하지 말고, to ~에 해당하는 42번 (Name: ubinos, Branch: ubinos-main) 만 check 하면, switch 버튼이 활성화 될 것입니다.

**Comment by siminsungho** [comment]
.
