### ISSUE TITLE
과제 작성 영상 중 make xmgr 실행시

### ISSUE THREAD

**Issue by hayoonJ** [ubinos/question_and_answer#13]
Executing task: make xmgr 

###############################################################################
# [Begin common-xmgr - hello_world_netduinoplus2_qemu]

: && cd ./ && python  "/c/Users/Yoon/ubiworks_mpc2024a_2019114358_jhy/library/ubinos/make/libmgr.py" --lib-absolute .. /c/Users/Yoon/ubiworks_mpc2024a_2019114358_jhy/library
Traceback (most recent call last):
  File "C:\Users\Yoon\ubiworks_mpc2024a_2019114358_jhy\library\ubinos\make\libmgr.py", line 25, in <module>
    from ttkwidgets import CheckboxTreeview
ModuleNotFoundError: No module named 'ttkwidgets'
make: *** [../library/ubinos/make/common.mk:343: common-xmgr] Error 1

이런 에러가 뜨면서 해당 창이 안뜹니다 혹시 어떻게 해야할까요?

**Comment by siminsungho** [comment]
시작 안내서의 "파이썬 설치하기"에 다음 명령을 실행해 ttkwidgets 등을 설치하는 과정이 있습니다.
이 과정을 수행하지 않은 것 같습니다.
이 과정 수행 후 다시 시도를~

**Comment by hayoonJ** [comment]
C:\Users\Yoon>pacman -S --needed base-devel git openssh mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-ccache
error: failed to init transaction (unable to lock database)
error: could not lock database: File exists
  if you're sure a package manager is not already
  running, you can remove /var/lib/pacman/db.lck

작년에 수업을 듣고 이번 학기가 재이수라 작동할 줄 알았는데 작동하지 않아 다시 검토하고 재설치 중인데 이런 오류가 뜹니다 혹시 어떻게 해야할지 알 수 있을까요? 주말에 질문드려 죄송합니다

**Comment by siminsungho** [comment]
안녕하세요.

Msys2 쪽이 꼬였네요.

 

컴퓨터 껐다가 다시 켜서 해보고, 

그래도 안 되면, MSYS2 terminal (예 MSYS2 UCRT64) 실행해서 다음 명령 실행 후 해보세요.

 

rm /var/lib/pacman/db.lck

 

그래도 안 되면, 설정 --> 앱 에서 msys2 삭제하고 다시 설치를~

 

그대로 안 되면, 연구실로~

**Comment by hayoonJ** [comment]
감사합니다!
