### ISSUE TITLE
cmd에  cd <my workspace directory> 실행하면 명령 구문이 올바르지 않다고 합니다.

### ISSUE THREAD

**Issue by kjm076060** [ubinos/question_and_answer#6]
뭐가 잘못된걸까요?

**Comment by siminsungho** [comment]
<my workspace directory>는 내가 작업용으로 사용하는 디렉토리를 입력하라는 뜻입니다.
만일 내가 작업 디렉토리로 C:\MyWorks 라는 디렉토리를 사용하면 다음과 같이 입력하면 됩니다.

cd C:\MyWorks

그리고, 만일 작업 디렉토리가 없다면 다음과 같이 입력해 작업 디렉토리를 만들어야 합니다.

mkdir C:\MyWorks

**Comment by siminsungho** [comment]
.
