### ISSUE TITLE
start debugging에서 진행이 어렵습니다.

### ISSUE THREAD

**Issue by iiiuuu1323** [ubinos/question_and_answer#7]
<img width="551" alt="스크린샷(226)" src="https://github.com/ubinos/question_and_answer/assets/163830634/91f6444d-67d2-47f6-9226-d621d3b6c453">

Hellow world 응용 예제 실행하기 4번에서
start debugging 이후 이러한 창이 뜨면서 진행이 안됩니다.

**Comment by siminsungho** [comment]
아래쪽 Panel의 Terminal tab에 나오는 메시지들을 전부 복사해서 올려주세요.

**Comment by iiiuuu1323** [comment]
아 죄송합니다 복사해서 올렸습니다.

###############################################################################
# [Begin common-build - hello_world_netduinoplus2_qemu]

: && cd "/c/myworks/ubiworks/ubiworks/output/hello_world_netduinoplus2_qemu" && make -j 16
make[1]: Entering directory '/c/myworks/ubiworks/ubiworks/output/hello_world_netduinoplus2_qemu'
[  0%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/bsp.c.obj
[  0%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/bsp.c.obj
[  1%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/board_memories.c.obj
[  2%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/board_memories.c.obj
[  2%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/bsp.c.obj
[  2%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/bsp.c.obj
[  3%] Building ASM object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/gcc_startup_sam9xe.S.obj
[  3%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/intr.c.obj
[  3%] Building ASM object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/gcc_startup_sam9xe.S.obj
[  4%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/intr.c.obj
[  4%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/lowlevel_init.c.obj
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
[  4%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/lowlevel_init.c.obj
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
[  5%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/pio.c.obj
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_errorterminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
[  5%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/system_sam9xe.c.obj
[  6%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/pio.c.obj
[  6%] Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/system_sam9xe.c.obj
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
make[3]: *** [CMakeFiles/ubinos.dir/build.make:104: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/bsp.c.obj] Error 127
make[3]: *** Waiting for unfinished jobs....
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:104: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/bsp.c.obj] Error 127
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:131: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/intr.c.obj] Error 127
make[3]: *** [CMakeFiles/ubinos.dir/build.make:131: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/intr.c.obj] Error 127
make[3]: *** [CMakeFiles/ubinos.dir/build.make:145: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/lowlevel_init.c.obj] Error 127
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
[  7%] make[3]: *** [CMakeFiles/ubiworks.dir/build.make:145: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/lowlevel_init.c.obj] Error 127
Building C object CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xexxxek/dtty.c.obj
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:90: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/board_memories.c.obj] Error 127
[  8%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xexxxek/dtty.c.obj
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
make[3]: *** [CMakeFiles/ubinos.dir/build.make:76: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/bsp.c.obj] Error 127
[  8%] Building C object CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/cortexm/bsp.c.obj
make[3]: *** [CMakeFiles/ubinos.dir/build.make:90: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/board_memories.c.obj] Error 127
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:76: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/bsp.c.obj] Error 127
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:159: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/pio.c.obj] Error 127
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:173: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/system_sam9xe.c.obj] Error 127
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:201: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/cortexm/bsp.c.obj] Error 127
make[3]: *** [CMakeFiles/ubinos.dir/build.make:173: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/system_sam9xe.c.obj] Error 127
make[3]: *** [CMakeFiles/ubiworks.dir/build.make:187: CMakeFiles/ubiworks.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xexxxek/dtty.c.obj] Error 127
make[3]: *** [CMakeFiles/ubinos.dir/build.make:187: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xexxxek/dtty.c.obj] Error 127
make[2]: *** [CMakeFiles/Makefile2:123: CMakeFiles/ubiworks.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/ubinos.dir/build.make:159: CMakeFiles/ubinos.dir/C_/myworks/ubiworks/ubiworks/library/ubinos/source/ubinos/bsp/arch/arm/classic/sam9xe/pio.c.obj] Error 127
make[2]: *** [CMakeFiles/Makefile2:97: CMakeFiles/ubinos.dir/all] Error 2
make[1]: *** [Makefile:91: all] Error 2
make[1]: Leaving directory '/c/myworks/ubiworks/ubiworks/output/hello_world_netduinoplus2_qemu'
make: *** [../library/ubinos/make/common.mk:252: common-build] Error 2

 *  The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command make rebuildd" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by ojh999** [comment]
저도 똑같은 이유로 진행이 되지 않습니다.

**Comment by siminsungho** [comment]
혹시 윈도우 계정에 한글이 포함되어 있나요?

**Comment by siminsungho** [comment]
VSCode에서 아래 파일을 연 다음,
ubiworks/make/Makefile

아래 부분을,
COMPILER_LAUNCHER ?= ccache

아래와 같이 변경하고,
# COMPILER_LAUNCHER ?= ccache

저장한 다음, 다시 시도해 보세요.

**Comment by siminsungho** [comment]
그리고, cmd를 연 후, 아래 명령 입력해서 출력되는 결과를 보내주세요.
(중요한 건 아니지만 윈도우 계정 명 같은 개인정보라고 할 수 있는 것들이 포함되어 있을 것이니, 메일로 보내주세요.)

**Comment by ojh999** [comment]
안녕하십니까!
마이크로프로세서002분반 수강중인 오재휘입니다.

사용자계정에 한글이 포함되어서 안된 것 같아 영어로 만들고 다시 실행하니 잘 되었습니다. 감사합니다.

그런데 공지사항에 올리신 강의자료 라이브러리 install 과정에서 run을 누르니 실패가 자꾸 뜨는데 어떻게 해결하는지 궁금합니다.
또한, 유노비스 라이브러리 최신화 과정 중 ubinos-main브랜치가 설치되지 않아서 스위치가 불가능한 것 같은데 혹시 큰 지장이
있을까요 교수님?

아침 일찍 답장해주셔서 감사합니다.

2024년 3월 21일 (목) 07:07, Sungho Park ***@***.***>님이 작성:

**Comment by siminsungho** [comment]
run을 누르면 run 버튼 바로 위의 text field에 실형 결과 메시지가 출력 됩니다.
그걸 복사해서 올려주세요.

**Comment by siminsungho** [comment]
그리고, cmd 창을 연 후, ubiworks 디렉토리로 들어 가서 (예: cd c:\myworks\ubiworks"
아래 명령 실행 후 그 결과를 보내주세요.

git status

git submodule foreach git status

git submodule foreach git branch -av

dir .\library\

dir .\.git\modules\library\

cat .\.gitmodules

**Comment by siminsungho** [comment]
그리고, install은 github.com에서 library를 가져오는 것이라 네트워크에 연결되어 있어야 정상 동작합니다~

**Comment by ojh999** [comment]
라이브러리 설치는 인터넷 문제였는지 해결되었습니다.
명령 실행 복사본입니다. 감사합니다!
C:\MyWorks\MyWorks\ubiworks>git status
On branch ubinos-main
Your branch is up to date with 'origin/ubinos-main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .gitmodules
        new file:   library/mp_course_materials


C:\MyWorks\MyWorks\ubiworks>git submodule foreach git status
Entering 'library/mp_course_materials'
On branch ubinos-main
Your branch is up to date with 'origin/ubinos-main'.

nothing to commit, working tree clean
Entering 'library/ubinos'
HEAD detached at 3bbc50b
nothing to commit, working tree clean

C:\MyWorks\MyWorks\ubiworks>git submodule foreach git branch -av
Entering 'library/mp_course_materials'
* ubinos-main                bde7c9f Add app config,
mp_course_ex0601_arm_thumb_interwork_sam9xe512ek_baremetal_with_fp.
  remotes/origin/HEAD        -> origin/ubinos-main
  remotes/origin/develop     bde7c9f Add app config,
mp_course_ex0601_arm_thumb_interwork_sam9xe512ek_baremetal_with_fp.
  remotes/origin/main        bde7c9f Add app config,
mp_course_ex0601_arm_thumb_interwork_sam9xe512ek_baremetal_with_fp.
  remotes/origin/ubinos-main bde7c9f Add app config,
mp_course_ex0601_arm_thumb_interwork_sam9xe512ek_baremetal_with_fp.
Entering 'library/ubinos'
* (HEAD detached at 3bbc50b) 3bbc50b Refactoring.
  ubinos-main                b5644e8 Fix build error.
  remotes/origin/HEAD        -> origin/ubinos-main
  remotes/origin/develop     b5644e8 Fix build error.
  remotes/origin/main        b5644e8 Fix build error.
  remotes/origin/master      b5644e8 Fix build error.
  remotes/origin/ubinos-main b5644e8 Fix build error.

C:\MyWorks\MyWorks\ubiworks>dir .\library\
 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2444-FD47

 C:\MyWorks\MyWorks\ubiworks\library 디렉터리

2024-03-21  오전 07:29    <DIR>          .
2024-03-21  오전 07:29    <DIR>          ..
2024-03-21  오전 07:29    <DIR>          mp_course_materials
2024-03-21  오전 07:28    <DIR>          ubinos
               0개 파일                   0 바이트
               4개 디렉터리  22,446,821,376 바이트 남음

C:\MyWorks\MyWorks\ubiworks>dir ..git\modules\library\
지정된 경로를 찾을 수 없습니다.

C:\MyWorks\MyWorks\ubiworks>cat ..gitmodules
cat: ..gitmodules: No such file or directory

2024년 3월 21일 (목) 오전 7:29, Sungho Park ***@***.***>님이 작성:

**Comment by siminsungho** [comment]
네~ 정상적인 상태로 보입니다.
그럼 계속 열심히~~

**Comment by ojh999** [comment]
교수님 make xsel 에서 mp_course_materialsdl 이 없어서 다시 이 라이브러리를 install하려고 똑같이 하였는데 failed 되었다고 뜹니다... Run위에 내용 복사해서 올리겠습니다.
git submodule add -f -b ubinos-main https://github.com/ubinos-edu/mp_course_materials.git ..\library\mp_course_materials
fatal: detected dubious ownership in repository at 'C:/MyWorks/ubiworks'
'C:/MyWorks/ubiworks' is owned by:
	DESKTOP-DA0CE2B/gg (S-1-5-21-1244142002-4036297112-696245406-1001)
but the current user is:
	DESKTOP-DA0CE2B/JH (S-1-5-21-1244142002-4036297112-696245406-1012)
To add an exception for this directory, call:

	git config --global --add safe.directory C:/MyWorks/ubiworks

**Comment by siminsungho** [comment]
그리고, cmd 창을 연 후, ubiworks 디렉토리로 들어 가서 (예: cd c:\myworks\ubiworks")
아래 명령 실행 후 그 결과를 보내주세요.

git status

git submodule foreach git status

git submodule foreach git branch -av

dir library

dir \.git\modules\library

cat \.gitmodules

**Comment by ojh999** [comment]
이렇게 뜹니다 교수님..
C:\MyWorks>cd ubiworks

C:\MyWorks\ubiworks>git status
fatal: detected dubious ownership in repository at 'C:/MyWorks/ubiworks'
'C:/MyWorks/ubiworks' is owned by:
        DESKTOP-DA0CE2B/gg (S-1-5-21-1244142002-4036297112-696245406-1001)
but the current user is:
        DESKTOP-DA0CE2B/JH (S-1-5-21-1244142002-4036297112-696245406-1012)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/MyWorks/ubiworks

C:\MyWorks\ubiworks>git submodule foreach git status
fatal: detected dubious ownership in repository at 'C:/MyWorks/ubiworks'
'C:/MyWorks/ubiworks' is owned by:
        DESKTOP-DA0CE2B/gg (S-1-5-21-1244142002-4036297112-696245406-1001)
but the current user is:
        DESKTOP-DA0CE2B/JH (S-1-5-21-1244142002-4036297112-696245406-1012)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/MyWorks/ubiworks

C:\MyWorks\ubiworks>git submodule foreach git branch -av
fatal: detected dubious ownership in repository at 'C:/MyWorks/ubiworks'
'C:/MyWorks/ubiworks' is owned by:
        DESKTOP-DA0CE2B/gg (S-1-5-21-1244142002-4036297112-696245406-1001)
but the current user is:
        DESKTOP-DA0CE2B/JH (S-1-5-21-1244142002-4036297112-696245406-1012)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/MyWorks/ubiworks

C:\MyWorks\ubiworks>dir library
 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2444-FD47

 C:\MyWorks\ubiworks\library 디렉터리

2024-03-20  오후 10:09    <DIR>          .
2024-03-20  오후 10:09    <DIR>          ..
2024-03-20  오후 10:09    <DIR>          ubinos
               0개 파일                   0 바이트
               3개 디렉터리  17,481,691,136 바이트 남음

C:\MyWorks\ubiworks>dir .git\modules\library
 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2444-FD47

 C:\MyWorks\ubiworks\.git\modules\library 디렉터리

2024-03-20  오후 10:09    <DIR>          .
2024-03-20  오후 10:09    <DIR>          ..
2024-03-20  오후 11:03    <DIR>          ubinos
               0개 파일                   0 바이트
               3개 디렉터리  17,481,633,792 바이트 남음

C:\MyWorks\ubiworks>cat .gitmodules
[submodule "library/ubinos"]
        path = library/ubinos
        url = https://github.com/ubinos/ubinos.git
        branch = ubinos-main

C:\MyWorks\ubiworks>

**Comment by siminsungho** [comment]
그리고... 
ubiworks 지우고 시작 안내서의 절차대로 새로 받은 후,
LMS의 공지사항 "마이크로프로세서 강의 자료 라이브러리 안내"에 적힌대로 mp_course_materials 라이브러리를 받아서 한 번 해보세요.

**Comment by ojh999** [comment]
ubiworks만 어떻게 다운하는지 모르겠습니다... 
금일 17시경에 연구실을 찾아뵈어도 될까요?

**Comment by siminsungho** [comment]
네~

**Comment by siminsungho** [comment]
.
